config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  get 'home/index'
  get '/cashes/:id/undo', to: 'cashes#undo'
  resources :monthlies
  resources :costumers
  resources :cashes

  root 'home#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/cash.rb
class Cash < ApplicationRecord

  monetize :price_cents

end

app/controllers/cashes_controller.rb
class CashesController < ApplicationController
  layout 'default'
  
  before_action :set_cash, only: [:show, :edit, :update, :destroy, :undo]

  # GET /cashes
  # GET /cashes.json
  def index
    @cashes = Cash.where("status = ?", false)
    @totalization = 0
    @cashes.each do |c| 
      @totalization += c.price
    end
  end

  # GET /cashes/1
  # GET /cashes/1.json
  def show; end

  # GET /cashes/new
  def new
    @cash = Cash.new
  end

  def undo
    @cash.status = true
    @cash.save
    redirect_to cashes_path, notice: 'Operação desfeita com sucesso.'
  end

  # GET /cashes/1/edit
  def edit; end

  # POST /cashes
  # POST /cashes.json
  def create
    @cash = Cash.new(cash_params)
    @cash.status = false
    respond_to do |format|
      if @cash.save
        format.html { redirect_to cashes_path, notice: 'Registro efetuado com sucesso.' }
        format.json { render :show, status: :created, location: @cash }
      else
        format.html { render :new }
        format.json { render json: @cash.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /cashes/1
  # PATCH/PUT /cashes/1.json
  def update
    respond_to do |format|
      if @cash.update(cash_params)
        format.html { redirect_to @cash, notice: 'Cash was successfully updated.' }
        format.json { render :show, status: :ok, location: @cash }
      else
        format.html { render :edit }
        format.json { render json: @cash.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /cashes/1
  # DELETE /cashes/1.json
  def destroy
    @cash.destroy
    respond_to do |format|
      format.html { redirect_to cashes_url, notice: 'Cash was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_cash
      @cash = Cash.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def cash_params
      params.require(:cash).permit(:price, :date, :kind, :note)
    end
end

app/helpers/cashes_helper.rb
module CashesHelper
end

app/views/cashes/_form.html.erb
<%= form_with(model: cash, local: true) do |form| %>
  <% if cash.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(cash.errors.count, "error") %> prohibited this cash from being saved:</h2>

      <ul>
        <% cash.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div class='row'>
      <div class='col s4'>
        <%= form.label :price, "Valor" %>
        <%= form.text_field :price %>
      </div>

      <div class='col s4'>
        <%= form.label :date, 'Data' %>
        <%= form.text_field :date, data: { behavior: "flatpickr" } %>
      </div>  
      <div class='col s4'>
        <label>
          <%= form.radio_button :kind, 'Receita' %>
          <span>Receita</span>
        </label>
        <label>
          <%= form.radio_button :kind, 'Despesa' %>
          <span>Despesa</span>
        </label>
      </div>
    </div>
    <div class='row'>
      <%= form.label :note, 'Observação' %>
      <%= form.text_area :note, class:'materialize-textarea' %>
    </div>
    <%= form.submit('Registrar', class: 'btn') %>
    <%= link_to 'Voltar', cashes_path, class:'btn' %>
<% end %>

app/views/cashes/edit.html.erb
<h1>Editing Cash</h1>

<%= render 'form', cash: @cash %>

<%= link_to 'Show', @cash %> |
<%= link_to 'Back', cashes_path %>

app/views/cashes/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Caixa</h1>

<table>
  <thead>
    <tr>
      <th>Valor</th>
      <th>Data</th>
      <th>Tipo</th>
      <th>Observação</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @cashes.each do |cash| %>
      <tr>
        <td><%= humanized_money_with_symbol(cash.price) %></td>
        <td><%= I18n.l(cash.date, format: :long) %></td>
        <td><%= cash.kind %></td>
        <td><%= cash.note %></td>
        <td><%= link_to 'Desfazer', "/cashes/#{cash.id}/undo" %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= label_tag "Total em caixa: R$#{@totalization}", nil, class:'btn btn-dark btn-color-white' %>
<%= link_to 'Nova Despesa/ Receita', new_cash_path, class:'btn btn-dark btn-color-white right' %>

app/views/cashes/new.html.erb
<div class='form-cash'>
  <h1 class='h1-center'>Caixa</h1>

  <%= render 'form', cash: @cash, class:'btn btn-danger' %>
</div>

app/views/cashes/old.erb
<%= simple_form_for :cash, method: :post do |f| %>
  <%= f.input :date, as: :string, input_html: { class: "datepicker" }%>
<% end %>

app/views/cashes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Value:</strong>
  <%= @cash.price %>
</p>

<p>
  <strong>Date:</strong>
  <%= @cash.date %>
</p>

<p>
  <strong>Kind:</strong>
  <%= @cash.kind %>
</p>

<p>
  <strong>Note:</strong>
  <%= @cash.note %>
</p>

<%= link_to 'Edit', edit_cash_path(@cash) %> |
<%= link_to 'Back', cashes_path %>