config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  get 'home/index'
  get '/cashes/:id/undo', to: 'cashes#undo'
  resources :monthlies
  resources :costumers
  resources :cashes

  root 'home#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/costumer.rb
class Costumer < ApplicationRecord
  has_one :address, dependent: :destroy
  accepts_nested_attributes_for :address, allow_destroy: true
end

app/controllers/costumers_controller.rb
class CostumersController < ApplicationController
  layout 'default'
  before_action :set_costumer, only: [:show, :edit, :update, :destroy]

  # GET /costumers
  # GET /costumers.json
  def index
    @costumers = Costumer.all
  end

  # GET /costumers/1
  # GET /costumers/1.json
  def show
  end

  # GET /costumers/new
  def new
    @costumer = Costumer.new
    @costumer.build_address
    @states = [ 'AC', 'AL', 'AP', 'AM', 'BA', 'CE', 'DF', 'ES', 'GO', 'MA', 'MT', 'MS', 'MG', 'PA', 
                'PB', 'PR', 'PE', 'PI', 'RJ', 'RN', 'RS', 'RO', 'RR', 'SC', 'SP', 'SE', 'TO' ]
  end

  # GET /costumers/1/edit
  def edit
    # @states = @costumer.address.state
  end

  # POST /costumers
  # POST /costumers.json
  def create
    @costumer = Costumer.new(costumer_params)

    respond_to do |format|
      if @costumer.save
        format.html { redirect_to @costumer, notice: 'Costumer was successfully created.' }
        format.json { render :show, status: :created, location: @costumer }
      else
        format.html { render :new }
        format.json { render json: @costumer.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /costumers/1
  # PATCH/PUT /costumers/1.json
  def update
    respond_to do |format|
      if @costumer.update(costumer_params)
        format.html { redirect_to @costumer, notice: 'Costumer was successfully updated.' }
        format.json { render :show, status: :ok, location: @costumer }
      else
        format.html { render :edit }
        format.json { render json: @costumer.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /costumers/1
  # DELETE /costumers/1.json
  def destroy
    @costumer.destroy
    respond_to do |format|
      format.html { redirect_to costumers_url, notice: 'Costumer was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_costumer
      @costumer = Costumer.find(params[:id])
      @states = @costumer.address.state
    end

    # Only allow a list of trusted parameters through.
    def costumer_params
      params.require(:costumer).permit(:name, :status, :rg, :cpf, :phone, 
                                       :mobile_phone, :date_of_birth,
                                        address_attributes: [
                                          :street,
                                          :district,
                                          :city,
                                          :number,
                                          :complement,
                                          :cep,
                                          :state,
                                          :_destroy
                                       ])
    end
end

app/helpers/costumers_helper.rb
module CostumersHelper
  def phone_format(phone)
    formated_phone = "("
    formated_phone << phone[0..1]
    formated_phone << ") "
    formated_phone << phone[2..5]
    formated_phone << "-"
    formated_phone << phone[6..9]
    formated_phone
  end

  def rg_format(rg)
    formated_rg = ""
    formated_rg << rg[0..1]
    formated_rg << '.'
    formated_rg << rg[2..4]
    formated_rg << '.'
    formated_rg << rg[5..7]
    formated_rg << '-'
    formated_rg << rg[8..9]
    formated_rg
  end

  def cpf_format(cpf)
    formated_cpf = ""
    formated_cpf << cpf[0..2]
    formated_cpf << '.'
    formated_cpf << cpf[3..5]
    formated_cpf << '.'
    formated_cpf << cpf[6..8]
    formated_cpf << '-'
    formated_cpf << cpf[9..10]
    formated_cpf
  end
end

app/views/costumers/_editform.html.erb
<%= form_with(model: costumer, local: true) do |form| %>
  <% if costumer.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(costumer.errors.count, "error") %> prohibited this costumer from being saved:</h2>

      <ul>
        <% costumer.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-row">
    <div class="form-group col-md-6">
      <%= form.label :name, 'Nome' %>
      <%= form.text_field :name, class:'form-control', placeholder: 'Nome' %>
    </div>
    <div class="form-group col-md-3">
      <%= form.label :rg, 'rg' %>
      <%= form.text_field :rg, class:'form-control', placeholder: 'RG' %>
    </div>
    <div class="form-group col-md-3">
      <%= form.label :cpf, 'cpf' %>
      <%= form.text_field :cpf, class:'form-control', placeholder:'CPF' %>
    </div>
  </div>
  <div class="form-row">
    <div class="field">
    </div>
    <div class="form-group col-md-3">
      <%= form.label :phone %>
      <%= form.text_field :phone, class:'form-control', placeholder:'(99) 9998-9999' %>
    </div>
    <div class="form-group col-md-3">
      <%= form.label :mobile_phone %>
      <%= form.text_field :mobile_phone, class:'form-control', placeholder:'(99) 98888-8888' %>
    </div>
    <div class="form-group col-md-3">
      <%= form.label :date_of_birth %>
      <%= form.date_field :date_of_birth %>
    </div>
    <div class="form-group col-md-3">
      <div class="form-check">
        <label>
          <%= form.check_box :status %>
          <span>Ativo</span>
        </label>
      </div>
    </div>

  </div>

  <%= form.fields_for :address do |ad| %>
    <div class='form-row'>
      <div class="form-group col-md-6">
        <%= ad.label :street, 'Rua' %>
        <%= ad.text_field :street, class:'form-control', placeholder:'Av. Brooklin' %>
      </div>
      <div class="form-group col-md-3">
        <%= ad.label :district, 'Bairro' %>
        <%= ad.text_field :district, class:'form-control', placeholder:'Jardim Europa' %>
      </div>
      <div class="form-group col-md-3">
        <%= ad.label :city, 'Cidade' %>
        <%= ad.text_field :city, class:'form-control', placeholder:'Leme' %>
      </div>
    </div>
    <div class="form-row">
      <div class="form-group col-md-1">
        <%= ad.label :number, 'Número' %>
        <%= ad.text_field :number, class:'form-control', placeholder:'156'%>
      </div>
      <div class="form-group col-md-5">
        <%= ad.label :complement, 'Complemento' %>
        <%= ad.text_field :complement, class:'form-control', placeholder:'Ap. 156'%>
      </div>
      <div class="form-group col-md-4">
        <%= ad.label :state %>
        <%= ad.text_field :state, class: 'form-control' %>
      </div>
      <div class="form-group col-md-2">
        <%= ad.label :cep, 'CEP' %>
        <%= ad.text_field :cep, class:'form-control'%>
      </div>
    </div>
  <% end %>

  <%= form.submit :class => 'btn btn-primary'  %>
  <%= link_to 'Voltar', costumers_path, class: 'btn btn-danger' %>
<% end %>

app/views/costumers/_form.html.erb
<%= form_with(model: costumer, local: true) do |form| %>
  <% if costumer.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(costumer.errors.count, "error") %> prohibited this costumer from being saved:</h2>

      <ul>
        <% costumer.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class='row'>
    <div class='col s6'>
      <%= form.label :name, 'Nome' %>
      <%= form.text_field :name, placeholder: 'Nome', class:'' %>
    </div>
    <div class='col s3'>
      <%= form.label :rg, 'RG' %>
      <%= form.text_field :rg, placeholder: 'RG', class:'' %>
    </div>
    <div class='col s3'>
      <%= form.label :cpf, 'CPF' %>
      <%= form.text_field :cpf, placeholder:'CPF', class:'' %>
    </div>
  </div>

  <div class='row'>
    <div class='col s3'>
      <%= form.label 'Telefone' %>
      <%= form.text_field :phone, placeholder:'(99) 9998-9999' %>
    </div>
    <div class='col s3'>
      <%= form.label 'Celular' %>
      <%= form.text_field :mobile_phone, class:'form-control', placeholder:'(99) 98888-8888' %>
    </div>
    <div class='col s3'>
      <%= form.label 'Nascimento' %>
      <%= form.text_field :date_of_birth, class:'datepicker' %>
    </div>
    <div class='col s3'>
      <label>
        <%= form.check_box :status %>
        <span>Ativo</span>
      </label>
    </div>
  </div>
  
  <%= form.fields_for :address do |ad| %>
    <div class='row'>
      <div class='col s6'>
        <%= ad.label :street, 'Rua' %>
        <%= ad.text_field :street, placeholder:'Av. Brooklin' %>
      </div>
      <div class='col s3'>
        <%= ad.label :number, 'Número' %>
        <%= ad.text_field :number %>
      </div>
      <div class='col s3'>
        <%= ad.label :complement, 'Complemento' %>
        <%= ad.text_field :complement %>
      </div>
    </div>
    <div class='row'>
      <div class='col s3'>
        <%= ad.label :district, 'Bairro' %>
        <%= ad.text_field :district %>
      </div>
      <div class='col s3'>
        <%= ad.label :city, 'Cidade' %>
        <%= ad.text_field :city %>
      </div>
      <div class='col s3'>
        <%= ad.label :state, 'Estado' %>
        <%= ad.text_field :state %>
      </div>
      <div class='col s3'>
        <%= ad.label :cep%>
        <%= ad.text_field :cep%>
      </div>
    </div>
  <% end %>

  <%= form.submit class: 'btn'%>
  <%= link_to 'Voltar', costumers_path, class:'btn' %>

<% end %>

app/views/costumers/edit.html.erb
<h1>Editing Costumer</h1>

<%= render 'editform', costumer: @costumer %>

app/views/costumers/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Associados</h1>

<table class='striped'>
  <thead>
    <tr>
      <th>Nome</th>
      <th>Status</th>
      <th>RG</th>
      <th>CPF</th>
      <th>Telefone</th>
      <th>Celular</th>
      <th>Nascimento</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @costumers.each do |costumer| %>
      <tr>
        <td><%= costumer.name %></td>
        <td><%= I18n.t costumer.status %></td>
        <td><%= rg_format(costumer.rg) %></td>
        <td><%= cpf_format(costumer.cpf) %></td>
        <td><%= phone_format(costumer.phone) %></td>
        <td><%= phone_format(costumer.mobile_phone) %></td>
        <td><%= I18n.l costumer.date_of_birth, format: :long %></td>
        <td><%= link_to 'Edit', edit_costumer_path(costumer) %></td>
        <!-- <td><%#= link_to 'Show', costumer %></td>
        <td><%#= link_to 'Destroy', costumer, method: :delete, data: { confirm: 'Are you sure?' } %></td> -->
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Cadastrar associado', new_costumer_path, class: 'btn btn-dark btn-color-white' %>

app/views/costumers/new.html.erb
<h3 class=''>Novo Associado</h3>

<%= render 'form', costumer: @costumer %>

app/views/costumers/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @costumer.name %>
</p>

<p>
  <strong>Status:</strong>
  <%= @costumer.status %>
</p>

<p>
  <strong>Rg:</strong>
  <%= @costumer.rg %>
</p>

<p>
  <strong>Cpf:</strong>
  <%= @costumer.cpf %>
</p>

<p>
  <strong>Phone:</strong>
  <%= @costumer.phone %>
</p>

<p>
  <strong>Mobile phone:</strong>
  <%= @costumer.mobile_phone %>
</p>

<p>
  <strong>Date of birth:</strong>
  <%= @costumer.date_of_birth %>
</p>

<%= link_to 'Edit', edit_costumer_path(@costumer) %> |
<%= link_to 'Back', costumers_path %>