config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  get 'home/index'
  get '/cashes/:id/undo', to: 'cashes#undo'
  resources :monthlies
  resources :costumers
  resources :cashes

  root 'home#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/monthly.rb
class Monthly < ApplicationRecord
  belongs_to :customer
end

app/controllers/monthlies_controller.rb
class MonthliesController < ApplicationController
  layout 'default'
  before_action :set_monthly, only: %i[show edit update destroy]

  # GET /monthlies
  # GET /monthlies.json
  def index
    @monthlies = Monthly.all
  end

  # GET /monthlies/1
  # GET /monthlies/1.json
  def show; end

  # GET /monthlies/new
  def new
    @monthly = Monthly.new
  end

  # GET /monthlies/1/edit
  def edit; end

  # POST /monthlies
  # POST /monthlies.json
  def create
    @monthly = Monthly.new(monthly_params)

    respond_to do |format|
      if @monthly.save
        format.html { redirect_to @monthly, notice: 'Monthly was successfully created.' }
        format.json { render :show, status: :created, location: @monthly }
      else
        format.html { render :new }
        format.json { render json: @monthly.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /monthlies/1
  # PATCH/PUT /monthlies/1.json
  def update
    respond_to do |format|
      if @monthly.update(monthly_params)
        format.html { redirect_to @monthly, notice: 'Monthly was successfully updated.' }
        format.json { render :show, status: :ok, location: @monthly }
      else
        format.html { render :edit }
        format.json { render json: @monthly.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /monthlies/1
  # DELETE /monthlies/1.json
  def destroy
    @monthly.destroy
    respond_to do |format|
      format.html { redirect_to monthlies_url, notice: 'Monthly was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  # Use callbacks to share common setup or constraints between actions.
  private

  def set_monthly
    @monthly = Monthly.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def monthly_params
    params.require(:monthly).permit(:status, :price, :date, :costumer_id)
  end
end

app/helpers/monthlies_helper.rb
module MonthliesHelper
end

app/views/monthlies/_form.html.erb
<%= form_with(model: monthly, local: true) do |form| %>
  <% if monthly.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(monthly.errors.count, "error") %> prohibited this monthly from being saved:</h2>

      <ul>
        <% monthly.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :status %>
    <%= form.text_field :status %>
  </div>

  <div class="field">
    <%= form.label :price %>
    <%= form.text_field :price %>
  </div>

  <div class="field">
    <%= form.label :date %>
    <%= form.date_select :date %>
  </div>

  <div class="field">
    <%= form.label :customer_id %>
    <%= form.text_field :customer_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/monthlies/edit.html.erb
<h1>Editing Monthly</h1>

<%= render 'form', monthly: @monthly %>

<%= link_to 'Show', @monthly %> |
<%= link_to 'Back', monthlies_path %>

app/views/monthlies/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Monthlies</h1>

<table>
  <thead>
    <tr>
      <th>Status</th>
      <th>Price</th>
      <th>Date</th>
      <th>Customer</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @monthlies.each do |monthly| %>
      <tr>
        <td><%= monthly.status %></td>
        <td><%= monthly.price %></td>
        <td><%= monthly.date %></td>
        <td><%= monthly.customer_id %></td>
        <td><%= link_to 'Show', monthly %></td>
        <td><%= link_to 'Edit', edit_monthly_path(monthly) %></td>
        <td><%= link_to 'Destroy', monthly, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Monthly', new_monthly_path %>

app/views/monthlies/new.html.erb
<h1>New Monthly</h1>

<%= render 'form', monthly: @monthly %>

<%= link_to 'Back', monthlies_path %>

app/views/monthlies/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Status:</strong>
  <%= @monthly.status %>
</p>

<p>
  <strong>Price:</strong>
  <%= @monthly.price %>
</p>

<p>
  <strong>Date:</strong>
  <%= @monthly.date %>
</p>

<p>
  <strong>Customer:</strong>
  <%= @monthly.customer_id %>
</p>

<%= link_to 'Edit', edit_monthly_path(@monthly) %> |
<%= link_to 'Back', monthlies_path %>